### ISSUE TITLE
[progress] FastAPI 서버에서 공강시간을 받아와 저장하는 로직 구현 진행 현황

### ISSUE THREAD

**Issue by hoonyworld** [GongGang-A-Bapjwo/GongGang-A-Bapjwo-SERVER#20]
## Progress Issue 📌

- FastAPI 서버에서 공강시간을 받아와 저장하는 로직을 구현합니다.
- 예상 구현 순서는 다음과 같습니다.

1. 클라이언트는 토큰과 이미지 파일을 포함하여 스프링 서버 API에 요청을 보냅니다.
2. 스프링 서버는 해당 이미지 파일을 S3 버킷에 업로드한 후, cloudfront에 배포합니다.
3. cloudfront URL은 토큰에서 추출한 memberId에 해당하는 데이터베이스의 튜플에 저장합니다.
4. 이후 CloudFront URL과 함께 필요한 데이터를 fastAPI 서버의 /uploadfile API로 OpenFeign을 통해 요청합니다.
5. fastAPI 서버는 해당 URL을 통해 이미지를 다운로드하고, 처리 후 Response DTO를 응답으로 반환합니다.
6. 파이썬 서버로부터 받은 응답 데이터를 엔티티 구조에 맞게 재구성하여 DB에 저장합니다.

<br>

## Todo ✔️

- [x] 클라이언트는 토큰과 이미지 파일을 포함하여 스프링 서버 API에 요청을 보냅니다.
- [x] 스프링 서버는 해당 이미지 파일을 S3 버킷에 업로드한 후, cloudfront에 배포합니다.
- [x] cloudfront URL은 토큰에서 추출한 memberId에 해당하는 데이터베이스의 튜플에 저장합니다.
- [x] 이후 CloudFront URL과 함께 필요한 데이터를 fastAPI 서버의 /uploadfile API로 OpenFeign을 통해 요청합니다.
- [x] fastAPI 서버는 해당 URL을 통해 이미지를 다운로드하고, 처리 후 Response DTO를 응답으로 반환합니다.
- [x]  파이썬 서버로부터 받은 응답 데이터를 엔티티 구조에 맞게 재구성하여 DB에 저장합니다.
