### ISSUE TITLE
[feat] OpenFeign을 활용해 FastAPI 서버와 Spring 서버 간 통신 구현

### ISSUE THREAD

**Issue by hoonyworld** [GongGang-A-Bapjwo/GongGang-A-Bapjwo-SERVER#25]
## Feature Issue 📌

- 이후 CloudFront URL과 함께 필요한 데이터를 fastAPI 서버의 /uploadfile API로 OpenFeign을 통해 요청합니다.
- fastAPI 서버는 해당 URL을 통해 이미지를 다운로드하고, 처리 후 Response DTO를 응답으로 반환합니다.
- 파이썬 서버로부터 받은 응답 데이터를 엔티티 구조에 맞게 재구성하여 DB에 저장합니다.

<br>

## Todo ✔️

- [x] 이후 CloudFront URL과 함께 필요한 데이터를 fastAPI 서버의 /uploadfile API로 OpenFeign을 통해 요청합니다.
- [x] fastAPI 서버는 해당 URL을 통해 이미지를 다운로드하고, 처리 후 Response DTO를 응답으로 반환합니다.
- [x] 파이썬 서버로부터 받은 응답 데이터를 엔티티 구조에 맞게 재구성하여 DB에 저장합니다.
