### ISSUE TITLE
[progress] 입장코드를 통해 들어온 공팟원들의 시간 교집합(잡기)을 구하는 로직을 구현 진행사항

### ISSUE THREAD

**Issue by hoonyworld** [GongGang-A-Bapjwo/GongGang-A-Bapjwo-SERVER#39]
## Progress Issue 📌

- 입장코드를 통해 들어온 공팟원들의 시간 교집합을 구하는 로직을 구현합니다.
- 예상 구현 순서는 다음과 같습니다.

1. 공팟장이 공팟방을 만들면, 입장코드(entranceCode)를 발급합니다.
2. 이때 entranceCode와 userId를 openfeign으로 fastAPI 서버의 `/entrance-codes`로 보냅니다.
3. fastAPI 서버는 notion DB에 요청받은 userId에 해당하는 튜플에 입장코드를 저장합니다. (python 코드 상 입장코드는 unique_url)
4. 공팟원들이 입장코드를 입력해서 공팟방에 입장합니다.
5. 이때 해당 공팟원의 userId와 entranceCode를 openfeign으로 fastAPI 서버의 POST `/entrance-codes`로 보냅니다.
6. fastAPI 서버는 notion DB에 요청받은 userId에 해당하는 튜플에 입장코드를 저장합니다. (python 코드 상 입장코드는 unique_url)
7. 스프링 서버에서 시간 잡기를 원하는 팟의 entranceCode와 roomId를 openfeign으로 fastAPI 서버의 GET `/meet` API로 보냅니다.
8. fastAPI 서버에서 유저의 입장 코드 리스트 중 인자로 요청된 entranceCode가 있는 유저들의 시간표를 이용해 시간 교집합을 구한 후 Response DTO를 응답으로 반환합니다.
9. fastAPI 서버로부터 받은 응답 데이터를 엔티티 구조에 맞게 재구성하여 클라이언트에게 보여줍니다.
10. 클라이언트가 유저가 선택한 시간을 보내주면, appointment_room 테이블에 decided_weekday와 decided_start_time, decided_end_time에 저장합니다.

<br>

## Todo ✔️

- [x] 공팟장이 공팟방을 만들면, 입장코드(entranceCode)를 발급합니다.
- [x] 이때 entranceCode와 userId를 openfeign으로 fastAPI 서버의 `/entrance-codes`로 보냅니다.
- [x] fastAPI 서버는 notion DB에 요청받은 userId에 해당하는 튜플에 입장코드를 저장합니다. (python 코드 상 입장코드는 unique_url)
- [x] 공팟원들이 입장코드를 입력해서 공팟방에 입장합니다.
- [x] 이때 해당 공팟원의 userId와 entranceCode를 openfeign으로 fastAPI 서버의 POST `/entrance-codes`로 보냅니다.
- [x] fastAPI 서버는 notion DB에 요청받은 userId에 해당하는 튜플에 입장코드를 저장합니다. (python 코드 상 입장코드는 unique_url)
- [x] 스프링 서버에서 시간 잡기를 원하는 팟의 entranceCode를 openfeign으로 fastAPI 서버의 GET `/meet` API로 보냅니다.
- [x] fastAPI 서버에서 유저의 입장 코드 리스트 중 인자로 요청된 entranceCode가 있는 유저들의 시간표를 이용해 시간 교집합을 구한 후 Response DTO를 응답으로 반환합니다.
- [x] fastAPI 서버로부터 받은 응답 데이터를 엔티티 구조에 맞게 재구성하여 클라이언트에게 보여줍니다.
- [x] 클라이언트가 유저가 선택한 시간을 보내주면, appointment_room 테이블에 decided_weekday와 decided_start_time, decided_end_time에 저장합니다.
